### ISSUE TITLE
Include artboard templates in design kit

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-design-kit#77] opened 2019-03-04 19:32 UTC
AFAIK, there's no current way to easily get the Carbon "2x grid" in Sketch with the 8px mini unit and layout columns.

When designing an app from scratch, I had to copy the artboard from an existing Sketch file to use the grid and layout.

Per [breakpoint guidance](https://next.carbondesignsystem.com/guidelines/layout#breakpoints):

> For best results, test designs and code at each of these standard breakpoints.

It'd be great if the design kit included templates of common browser viewport widths (per our recommended layout breakpoints) and grids (e.g. columns and rows with gutters, without gutters, etc.)

**Comment by aagonzales** [comment] 2019-03-04 21:15
We do have them in the Kit the problem is its not a symbol and therefore not accessible through the   Sketch Library. They can be added manually by the user through [Sketch Templates ](https://sketchapp.com/docs/templates/) but its not involves more steps outside of adding the one-click to install library action.

![image](https://user-images.githubusercontent.com/11670886/53763171-a621f700-3e8f-11e9-8fff-4dc3682d5274.png)

**Comment by aagonzales** [comment] 2019-04-30 19:08
Grid can now be added as a Sketch Template: https://sketch.cloud/s/ngV7z
Without building a plug-in there is no easy way to automatically get the grid except to start or copy/paste from the sketch template. 

Getting and setting up the grid template is also part of the getting started flow: https://www.carbondesignsystem.com/getting-started/designers#get-the-kit

**Comment by aagonzales** [comment] 2019-04-30 19:09
Closing for now since we've done as much as we can on this topic without building a plug-in.

**Closed by aagonzales** 2019-04-30 19:09 UTC
Labels: project: design-kit
