### ISSUE TITLE
Carbon Design System Sketch library breadcrumbs force spacer "on"

### ISSUE THREAD

**Issue by lnajjar** [carbon-design-system/carbon-design-kit#215] opened 2019-10-15 15:51 UTC
## Detailed description

Today's Carbon Design System Sketch library updates turned the breadcrumb "spacing-03 (8px)" "on" even when it is set to "off." All my breadcrumbs have unwanted extra spaces.

> What version of the Carbon Design System Kit are you using?
Well, I downloaded today's updates, so I suppose I have the latest version.

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.
Breadcrumb. Spacer.

> What did you expect to happen? What happened instead? What would you like to see changed?
I expected my breadcrumbs to remain the same. After today's updates, spacers were inserted after each breadcrumb phrase in a breadcrumb. Please fix the bug. Turn the breadcrumb "spacing-03 (8px)" to "off" when it is set to "off."

## Steps to reproduce the issue

1. Accept today's Carbon Design System Sketch library updates
2. Notice that all the breadcrumbs in your design got messed up with extra, unwanted spacers

## Additional information

* Screenshots or Sketch file links
* Notes
![Screen Shot 2019-10-15 at 10 34 20 AM](https://user-images.githubusercontent.com/12902530/66846987-4537c280-ef38-11e9-954b-29f042968d61.png)

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized (i.e.use the `libraries` label for any issue relating to the Carbon Sketch Library). This will help us to better understand and address your issue.

**Comment by aagonzales** [comment] 2019-10-21 16:53
This bug was caused by the latest Sketch update. This is now fixed in our kit.

10.7

**Closed by aagonzales** 2019-10-21 16:53 UTC
Labels: kit: sketch, type: bug 🐛
