### ISSUE TITLE
Text entry fields should not show "Placeholder text"

### ISSUE THREAD

**Issue by lnajjar** [carbon-design-system/carbon-design-kit#230] opened 2019-11-14 19:50 UTC
## Detailed description

During a recent Carbon Design System Sketch library update, the text area fields I had set as empty by entering a space in the text area now show the default "Placeholder text" text that I replaced with the space.

Will you please fix this regression error? Will you please do more complete quality assurance testing before you send an update that undoes my design work?

> What version of the Carbon Design System Kit are you using?
Latest

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.
Text area

> What did you expect to happen? What happened instead? What would you like to see changed?
Do not add back in the "Placeholder text" that I had removed by entering a space in the text areas

> Is this issue being filed based on a discrepancy between the website/code and the kit? If so what is the inconsistency?

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or Sketch file links
* Notes

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized (i.e.use the `libraries` label for any issue relating to the Carbon Sketch Library). This will help us to better understand and address your issue.

![image](https://user-images.githubusercontent.com/12902530/68890878-6b8e8080-06e5-11ea-8223-4196e3796fc9.png)

**Comment by lnajjar** [comment] 2019-11-20 23:25
Hi @laurenmrice , this regression error occurs easily 50 times in my 86 enterprise application wireframes. I cannot demo my work to prospective customers. Every time I demo to colleagues I have to explain the regression error. For example:

![image](https://user-images.githubusercontent.com/12902530/69287029-67b59f00-0bba-11ea-856f-9d01e068776f.png)

If it is any help, if I add a space at the end of the problematic placeholder text, my typed in text usually displays:

![image](https://user-images.githubusercontent.com/12902530/69287124-bbc08380-0bba-11ea-88eb-dd65d747b8e6.png)

Bizarre, right?

Could you please tell me when this regression error may be assigned to someone?

If you want to see it live, I am happy to do a Skype or Webex with you.

**Comment by laurenmrice** [comment] 2019-11-21 15:40
So just to clarify, the inputs you purposely set to be empty have now defaulted to have the placeholder text in it? I honestly think this is a Sketch bug and not something we can fix from our end unfortunately.

**Comment by lnajjar** [comment] 2019-11-21 17:45
Yes, the inputs I purposely set to be empty have now defaulted to have the "Placeholder text" in it.

I do not think this is a Sketch error because the problems I describe below occurred immediately after I accepted Carbon Design System updates.

@laurenmrice , will you please follow the steps below to confirm the regression errors?


Placeholder text remains even after being replaced with a space:
1. Perform Sketch > Carbon Design System (White theme) > text input > default > 01 label only > 01 enabled and drag the text input onto the page
![image](https://user-images.githubusercontent.com/12902530/69361454-21ac1a00-0c52-11ea-92c3-227f2225acab.png)

2. In the Sketch Inspector on the right side of the page, replace the "Placeholder text" with a space
![image](https://user-images.githubusercontent.com/12902530/69361506-3dafbb80-0c52-11ea-8b4b-621f04f2ac29.png)

3. Note that "Placeholder text" disappears from the Sketch Inspector on the right side of the page but remains on the Carbon Design System text input on the Sketch canvas
![image](https://user-images.githubusercontent.com/12902530/69361594-6d5ec380-0c52-11ea-949d-08630797c9d6.png)


Placeholder text obliterates text that was in the text input field:
1. Click on a text input that included text before the Carbon Design System update
![image](https://user-images.githubusercontent.com/12902530/69361859-ef4eec80-0c52-11ea-8b0f-fe5f534c5da3.png)

2. Note that the Sketch canvas shows "Placeholder text" in the text input but the Sketch Inspector shows " FY 2019 statistics actuals data "
![image](https://user-images.githubusercontent.com/12902530/69361924-15748c80-0c53-11ea-89e0-c414c4b13a02.png)

3. Perform Sketch > Carbon Design System (White theme) > text input > default > 01 label only > 01 enabled to drag a new text input onto the Sketch canvas. Type some text into the Sketch Inspector text input "Placeholder text" field. Note that the new text is not displayed on the Carbon Design System text input user interface control.
![image](https://user-images.githubusercontent.com/12902530/69362094-756b3300-0c53-11ea-98cc-882352b62cc8.png)

So, it appears that the updated Carbon Design System text input user interface control:
1. Broke the existing text input user interface controls in my design
2. Prevents me from replacing the broken text input fields with new text input fields.

@laurenmrice , will you please duplicate these steps for yourself then ask for the regression errors to be fixed?

**Comment by lnajjar** [comment] 2019-11-21 21:21
Looks like the Carbon Design System update that came out two minutes ago may have fixed the problems. I'll let you know if not.

So, not a Sketch problem. @laurenmrice , will you please check Carbon Design System before blaming your users or Slack?

**Comment by laurenmrice** [comment] 2019-11-21 21:28
I have been actively trying to help solve this problem today. I am not blaming Sketch, was just considering it could be a Sketch problem given the new 59, 60 and 60.1 updates that sometimes cause bugs in our Carbon kits and we are not aware of them sometimes until users let us know about them, which is helpful.

**Comment by chrisconnors-ibm** [comment] 2019-11-21 23:21
@inajjar Thanks for taking the time to submit this issue. Unfortunately we are unable to reproduce this error following your guidance as described, and are closing this issue "unable to reproduce."

I'm sorry recent Sketch app updates have adversely affected kits (including ours) and your work. We do not have early access to their releases there’s no possibility for us to anticipate these changes. Their new features, in particular SmartLayout, have are significant, and have been impacting a lot of users. They do not have a repo for issues but you can [submit feedback here](https://www.sketch.com/support/troubleshooting/providing-feedback/).

**Closed by chrisconnors-ibm** 2019-11-21 23:21 UTC
Labels: kit: sketch, type: bug 🐛

**Comment by lnajjar** [comment] 2019-11-22 16:02
@chrisconnors-ibm , as a representative of IBM Carbon Design System, could you please let Sketch know that their update messed up Carbon Design System Sketch Kit?

Using the link you provided above, I sent them feedback.

What I expect is that Sketch will blame the Carbon Design System Sketch Kit and the Carbon Design System Sketch Kit will blame Sketch. So, the very significant problems will not get fixed for your users.

**Comment by chrisconnors-ibm** [comment] 2019-11-22 16:27
I'm sorry, but since we are unable to reproduce this, we have nothing material to report here.
