### ISSUE TITLE
[UI shell left panel] carbon figma kit

### ISSUE THREAD

**Issue by mariuszmickiewicz** [carbon-design-system/carbon-design-kit#486] opened 2022-01-15 16:29 UTC
There are some small things I've noticed on the _UI shell left panel_ component:

1. _Link level 2 selected_ state is not using semibold weight.

![image](https://user-images.githubusercontent.com/12408951/149629181-a203921d-7a6a-40c6-a68f-5a5dd7e4a9f2.png)

| Should be | Currently is |
| ---------- |  ----------- |
| ![image](https://user-images.githubusercontent.com/12408951/149629164-e2de043b-fc41-4b15-a1b6-e67b559c57d6.png) |  ![image](https://user-images.githubusercontent.com/12408951/149630406-0e78fb01-9065-447c-8296-24fe040300d8.png) |

2. A _divider_ state in the Figma kit is 32px high while in Sketch kit and currently built it is:
![image](https://user-images.githubusercontent.com/12408951/149629327-4f765f65-7653-4e93-ad95-d86906756d53.png)
also see the other two images above for comparison. 17px is not a nice number, but this way the divider is not put on a half pixel and it is rendered nicely also on non retina screens). I'm currently on PC, so you can see on the "currently is" picture that divider looks higher and a bit blurred.

3. If a menu is open and its child is in a selected state, the menu header/parent should be $text-01, not $text-02 (it is kind of silently selected) - see _Portal_ on the images above.

4. I can't find the state for the menu item where an icon in on the right side. See the example here: [Github](https://www.carbondesignsystem.com/all-about-carbon/what-is-carbon/) item at the bottom of the side panel. In my product we also use this state on level 2 (see "View portal" item on "Should be" image). 

5. Seem to me (maybe I'm doing something wrong) that _Link + icon level 2_ has the icon hidden by default.

Thanks for looking into this!

**Comment by juanencalada** [comment] 2022-01-30 23:38
Hi @mariuszmickiewicz, thanks for bringing all of these to our attention. I've addressed these issues and updated the library. For number 5, it's certainly confusing how we have it named, but it does display as intended. "Link + Icon, Level 2" refers to a level 2 item, that has a level 1 parent with an icon. We've tried many different naming patterns to help make this clear to understand, so if you have any ideas please let us know. For now, I will close this issue since the other items which we can take immediate action on have been addressed.

**Closed** 2022-01-30 23:39 UTC
Labels: type: bug 🐛, kit: figma
