### ISSUE TITLE
Missing notification status icons in Figma kit

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-design-kit#812] opened 2024-05-10 13:53 UTC
`info-square` and `warning-alt` missing from Figma kit for Notification

<img width="144" alt="Screenshot 2024-05-10 at 8 52 21 AM" src="https://github.com/carbon-design-system/carbon/assets/2753488/29c8dd84-9455-4b9f-8872-ea6199fe15fe">
<img width="128" alt="Screenshot 2024-05-10 at 8 52 29 AM" src="https://github.com/carbon-design-system/carbon/assets/2753488/c2964aa3-a275-43d8-9a86-0d296f1ee10a">

https://react.carbondesignsystem.com/?path=/story/components-notifications-inline--playground&args=kind:warning-alt

**Comment by laurenmrice** [comment] 2024-06-13 14:37
After a backlog cleaning call, designers were not sure where this enhancement came from, so we need to investigate it.
- [x] Look at Telemetry to see where these are being used. 
- [x] Track down when these were added to the system.
  - [ ] Alison found the [original PR](https://github.com/carbon-design-system/carbon/pull/6103) which was approved by design. So let's decide on if we should add these in as "alternatives" to the default informational and warning notifications we provide.

**Comment by sstrubberg** [comment] 2024-07-10 14:17
@benjamin-kurien to follow up.

**Comment by benjamin-kurien** [comment] 2024-07-18 15:23
@sstrubberg 
Checked all time data with Telemetry - for the relative distribution of how the following icons were used within inline notifications.

- error: 50.2%
- info: 27.74%
- info-square: nil
- success: 6.48%
- warning: 15.59%
- warning-alt: 0% (must be used few times)

Since both info-square, and warning-alt have not been used, removing them from our system wouldnt have major impacts.

**Comment by laurenmrice** [comment] 2024-07-24 14:14
We are going to deprecate these alternative status inline notifications, so closing as not planned.

**Closed by laurenmrice** 2024-07-24 14:14 UTC
Labels: type: bug 🐛, status: blocked 🙅‍♀️, severity: 2, kit: figma, role: design :pencil2:, component: notification
